"""Generate dummy CoreTax demo PDFs for the Knowledge Store upload demo.

Usage:
    python3 docs/generate_demo_pdfs.py

Produces five PDFs under `docs/demo_uploads/`:

  * CoreTax_BRD.pdf              - Business Requirements Document
  * CoreTax_FSD.pdf              - Functional Specification Document
  * CoreTax_TSD.pdf              - Technical Specification Document
  * CoreTax_Deployment_Guide.pdf - Deployment runbook (envs, infra, secrets)
  * CoreTax_CICD_Pipeline.pdf    - CI/CD pipeline + release process

These are intentionally fictional demo content — none of it represents
real DJP procedures. They exist purely so the "Upload File" tab in the
Knowledge Store has realistic material to ingest during product demos.
"""

from __future__ import annotations

from pathlib import Path
from datetime import datetime

from fpdf import FPDF
from fpdf.enums import XPos, YPos


OUTPUT_DIR = Path(__file__).resolve().parent / "demo_uploads"


# ── PDF helper ────────────────────────────────────────────────────────────


class DemoPDF(FPDF):
    """Thin FPDF wrapper that gives us a header/footer and easy section
    helpers. All text is latin-1 safe so the built-in helvetica works."""

    def __init__(self, title: str, doc_code: str):
        super().__init__()
        self.title_text = title
        self.doc_code = doc_code
        self.set_auto_page_break(auto=True, margin=18)
        self.set_margins(18, 22, 18)

    def header(self):
        if self.page_no() == 1:
            return  # title page handles its own layout
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(80, 80, 80)
        self.cell(0, 6, self.title_text, new_x=XPos.RIGHT, new_y=YPos.TOP)
        self.set_font("Helvetica", "", 8)
        self.cell(
            0,
            6,
            self.doc_code,
            align="R",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
        )
        self.set_draw_color(180, 180, 180)
        self.line(self.l_margin, 18, self.w - self.r_margin, 18)
        self.ln(6)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(
            0,
            6,
            f"DJP CoreTax | {self.doc_code} | Page {self.page_no()}",
            align="C",
        )
        self.set_text_color(0, 0, 0)

    # Section helpers ----------------------------------------------------

    def title_page(self, title: str, subtitle: str, doc_code: str, version: str):
        self.add_page()
        self.set_y(60)
        self.set_font("Helvetica", "B", 22)
        self.multi_cell(
            0, 12, title, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )
        self.ln(6)
        self.set_font("Helvetica", "", 13)
        self.multi_cell(
            0, 7, subtitle, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )
        self.ln(20)

        # Metadata box
        self.set_font("Helvetica", "B", 10)
        meta = [
            ("Document Code", doc_code),
            ("Version", version),
            ("Status", "DRAFT - Demo Content"),
            ("Owner", "DJP CoreTax Programme"),
            ("Issued", datetime.now().strftime("%d %B %Y")),
            ("Classification", "Internal - Demonstration Only"),
        ]
        col_w = 170
        for label, value in meta:
            self.set_x((self.w - col_w) / 2)
            self.set_font("Helvetica", "B", 10)
            self.cell(55, 7, label, border=1)
            self.set_font("Helvetica", "", 10)
            self.cell(col_w - 55, 7, value, border=1)
            self.ln()

        self.ln(15)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(120, 120, 120)
        self.multi_cell(
            0,
            5,
            "This is a synthetic document generated by Lumen.AI to "
            "demonstrate the Knowledge Store upload-and-ingest workflow. "
            "It does not reflect any actual DJP CoreTax requirement, design "
            "or operational procedure.",
            align="C",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
        )
        self.set_text_color(0, 0, 0)

    def h1(self, text: str):
        self.ln(4)
        self.set_font("Helvetica", "B", 16)
        self.multi_cell(
            0, 8, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )
        self.ln(2)

    def h2(self, text: str):
        self.ln(3)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(20, 60, 120)
        self.multi_cell(
            0, 6, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )
        self.set_text_color(0, 0, 0)
        self.ln(1)

    def para(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.multi_cell(
            0, 5, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )
        self.ln(1)

    def bullets(self, items: list):
        self.set_font("Helvetica", "", 10)
        for it in items:
            self.set_x(self.l_margin + 4)
            self.multi_cell(
                0, 5, "- " + it, new_x=XPos.LMARGIN, new_y=YPos.NEXT
            )
        self.ln(1)

    def table(self, headers: list, rows: list, col_widths: list = None):
        self.set_font("Helvetica", "B", 9)
        page_w = self.w - self.l_margin - self.r_margin
        if not col_widths:
            col_widths = [page_w / len(headers)] * len(headers)
        self.set_fill_color(220, 230, 240)
        for h, w in zip(headers, col_widths):
            self.cell(w, 6, h, border=1, fill=True)
        self.ln()
        self.set_font("Helvetica", "", 9)
        for row in rows:
            for c, w in zip(row, col_widths):
                self.cell(w, 5.5, str(c)[:60], border=1)
            self.ln()
        self.ln(2)


# ── Document builders ────────────────────────────────────────────────────


def build_brd() -> DemoPDF:
    p = DemoPDF("CoreTax Business Requirements", "BRD-CT-2026-001")
    p.title_page(
        "CoreTax Modernisation Programme",
        "Business Requirements Document",
        "BRD-CT-2026-001",
        "1.0",
    )

    p.add_page()
    p.h1("1. Executive Summary")
    p.para(
        "The CoreTax modernisation programme replaces the legacy assessment "
        "and collection platform with a microservices-based architecture "
        "that handles taxpayer registration, tax filing, billing, payment, "
        "compliance scoring, and audit traceability for both VAT and "
        "income-tax obligations. This document captures the business "
        "drivers, scope, success criteria, and high-level capabilities "
        "expected from the new platform."
    )

    p.h1("2. Business Objectives")
    p.bullets([
        "Reduce average taxpayer registration cycle time from 5 working days to under 30 minutes.",
        "Provide a unified single-view of taxpayer obligations across VAT, income tax and luxury goods tax.",
        "Enable straight-through processing for at least 80 percent of routine VAT filings without officer review.",
        "Increase voluntary compliance rate by 12 percent within 18 months of go-live.",
        "Reduce monthly reconciliation effort across 33 regional offices by at least 60 percent.",
        "Provide secure, auditable digital channels for both taxpayers and tax officers.",
    ])

    p.h1("3. Scope")
    p.h2("3.1 In Scope")
    p.bullets([
        "Taxpayer onboarding, NPWP issuance, KYC validation, and profile maintenance.",
        "VAT, Income Tax, Luxury Goods Tax filing, calculation and submission workflows.",
        "Billing code generation, payment ingestion, reconciliation with bank channels.",
        "Compliance scoring engine with risk-based audit triggers.",
        "Notification engine for SMS, email and in-app delivery.",
        "Officer back-office portal for case management, exemptions and adjustments.",
        "Public REST API surface for partner integrations and reporting.",
    ])
    p.h2("3.2 Out of Scope")
    p.bullets([
        "Customs duties (handled by the separate DJBC platform).",
        "Local government levies and regional retributions.",
        "Direct integration with foreign tax administrations.",
    ])

    p.h1("4. Stakeholders")
    p.table(
        ["Stakeholder", "Role", "Primary Interest"],
        [
            ["Direktur Jenderal Pajak", "Programme Sponsor", "Strategic outcomes, compliance lift"],
            ["Kepala Kantor Pelayanan Pajak", "Operational Owner", "Officer productivity, case throughput"],
            ["CIO Office", "Delivery Owner", "Architecture, security, sustainability"],
            ["Wajib Pajak (Taxpayers)", "End User", "Self-service, transparency, speed"],
            ["Bank Persepsi Partners", "External Integrator", "Settlement reliability, reconciliation"],
            ["Internal Audit", "Assurance", "Auditability, segregation of duties"],
        ],
        [55, 55, 70],
    )

    p.add_page()
    p.h1("5. High-Level Requirements")
    p.h2("5.1 Functional Capabilities")
    p.bullets([
        "BR-001 The system shall support online and assisted taxpayer registration including KYC document upload.",
        "BR-002 The system shall validate NPWP format and uniqueness in real time during registration.",
        "BR-003 The system shall calculate VAT, income tax and luxury goods tax obligations from submitted line items.",
        "BR-004 The system shall generate a unique billing code per obligation, valid for the configured payment window.",
        "BR-005 The system shall accept payment confirmations from authorised Bank Persepsi channels and reconcile within 5 minutes.",
        "BR-006 The system shall maintain a complete audit trail of every state change for the statutory retention period.",
        "BR-007 The system shall support officer-initiated adjustments with mandatory dual control above a configurable threshold.",
        "BR-008 The system shall emit standard events to subscribed downstream systems on registration, filing, payment and adjustment.",
    ])

    p.h2("5.2 Non-Functional")
    p.bullets([
        "NFR-001 99.9 percent monthly availability for the public taxpayer channel.",
        "NFR-002 95th percentile API response time below 800 ms under nominal load.",
        "NFR-003 Horizontal scalability to support 25 million active taxpayers and 4 million concurrent monthly filers.",
        "NFR-004 Conformance with national data protection (UU PDP) and ISO 27001 controls.",
        "NFR-005 Recovery time objective of 30 minutes; recovery point objective of 5 minutes.",
        "NFR-006 Bilingual user interface (Bahasa Indonesia primary, English secondary).",
    ])

    p.h1("6. Success Criteria")
    p.bullets([
        "All in-scope capabilities deployed to production and accepted by the operational owner.",
        "Pilot population of 50 000 taxpayers onboarded with measured net promoter score above 35.",
        "Two consecutive monthly reconciliation cycles closed without manual intervention.",
        "Independent security review with no critical findings outstanding at go-live.",
    ])

    p.h1("7. Assumptions and Constraints")
    p.bullets([
        "The existing taxpayer master file is migratable through a one-time ETL pass.",
        "All Bank Persepsi partners can issue settlement events over a secure REST or messaging channel.",
        "Hosting will be on the national government cloud with private connectivity to partner banks.",
        "Programme funding is approved annually and contingent on quarterly milestone reviews.",
    ])

    return p


def build_fsd() -> DemoPDF:
    p = DemoPDF("CoreTax Functional Specification", "FSD-CT-2026-002")
    p.title_page(
        "CoreTax Modernisation Programme",
        "Functional Specification Document",
        "FSD-CT-2026-002",
        "1.0",
    )

    p.add_page()
    p.h1("1. Purpose")
    p.para(
        "This Functional Specification Document elaborates the requirements "
        "captured in BRD-CT-2026-001 into concrete functional behaviours "
        "for each subdomain of the CoreTax platform. Each section describes "
        "the actors, preconditions, primary flow, alternate flows and "
        "post-conditions for the use cases the engineering teams will "
        "implement."
    )

    p.h1("2. Subdomain Map")
    p.table(
        ["Subdomain", "Primary Microservice", "Owning Team"],
        [
            ["Registration", "RegistrationService", "Identity Squad"],
            ["Filing", "FilingService", "Compliance Squad"],
            ["Billing", "BillingService", "Revenue Squad"],
            ["Payment", "PaymentService", "Revenue Squad"],
            ["Compliance", "ComplianceService", "Risk Squad"],
            ["Notification", "NotificationService", "Platform Squad"],
            ["Audit Trail", "AuditService", "Platform Squad"],
        ],
        [55, 70, 55],
    )

    p.h1("3. Use Case: Taxpayer Registration")
    p.h2("3.1 Actors")
    p.bullets([
        "Primary: prospective Wajib Pajak (individual or corporate).",
        "Secondary: KYC verification provider, officer reviewer (only for corporate cases).",
    ])
    p.h2("3.2 Preconditions")
    p.bullets([
        "Applicant has a valid national identity document (KTP or paspor).",
        "Applicant has a verified mobile phone number.",
    ])
    p.h2("3.3 Primary Flow")
    p.bullets([
        "1. Applicant opens the public registration portal and selects the taxpayer category.",
        "2. RegistrationService presents the appropriate form and validates each field on submit.",
        "3. The service requests KYC verification through the configured provider and waits asynchronously.",
        "4. On success, RegistrationService allocates an NPWP using the configured numbering rules.",
        "5. The service publishes a TaxpayerRegistered event to the message bus.",
        "6. NotificationService sends an SMS and email confirmation containing the activation link.",
    ])
    p.h2("3.4 Alternate Flows")
    p.bullets([
        "A1: KYC provider returns inconclusive - case is routed to officer manual review.",
        "A2: Duplicate identity detected - applicant is offered the merge-or-recover flow.",
        "A3: Provider unreachable - case is queued and retried with exponential backoff.",
    ])
    p.h2("3.5 Post-conditions")
    p.bullets([
        "Taxpayer record persisted with status ACTIVE or PENDING_REVIEW.",
        "TaxpayerRegistered event durably published exactly once.",
        "Audit entries written to AuditService.",
    ])

    p.add_page()
    p.h1("4. Use Case: VAT Filing Submission")
    p.h2("4.1 Actors")
    p.bullets([
        "Primary: registered Wajib Pajak Badan submitting periodic VAT (PPN) filing.",
        "Secondary: tax officer reviewing flagged filings.",
    ])
    p.h2("4.2 Primary Flow")
    p.bullets([
        "1. Taxpayer authenticates via the portal and chooses 'Submit PPN'.",
        "2. FilingService loads the draft (if any) and accepts the new line items.",
        "3. The service calls the calculation engine to compute payable, credit and refund balances.",
        "4. Taxpayer confirms; FilingService persists the filing in state SUBMITTED.",
        "5. FilingService publishes a FilingSubmitted event consumed by BillingService.",
        "6. BillingService produces a billing code and pushes a BillingCodeIssued event.",
        "7. NotificationService delivers the billing code to the taxpayer.",
    ])
    p.h2("4.3 Validation Rules")
    p.bullets([
        "All line items must reference an active VAT rate effective on the period date.",
        "Total payable must equal sum(line.taxableAmount * line.rate) within 1 IDR rounding tolerance.",
        "Credits carried forward cannot exceed the prior period closing balance.",
    ])

    p.h1("5. Use Case: Payment Reconciliation")
    p.h2("5.1 Primary Flow")
    p.bullets([
        "1. Bank Persepsi partner posts a settlement event over the configured channel.",
        "2. PaymentService correlates the event to an open billing code and marks it PAID.",
        "3. PaymentService publishes a PaymentReceived event.",
        "4. ComplianceService updates the taxpayer compliance score.",
        "5. AuditService records the state transition with the bank reference number.",
    ])

    p.h1("6. Cross-cutting Behaviours")
    p.bullets([
        "All inbound HTTP endpoints require a bearer token issued by the corporate identity provider.",
        "All published events follow the standard envelope: id, type, occurredAt, version, payload.",
        "Idempotency keys are enforced on all state-changing endpoints for 24 hours.",
        "Localised messages are sourced from the resource bundle and never hard-coded in services.",
    ])

    return p


def build_tsd() -> DemoPDF:
    p = DemoPDF("CoreTax Technical Specification", "TSD-CT-2026-003")
    p.title_page(
        "CoreTax Modernisation Programme",
        "Technical Specification Document",
        "TSD-CT-2026-003",
        "1.0",
    )

    p.add_page()
    p.h1("1. Architecture Overview")
    p.para(
        "CoreTax is built as a set of bounded-context microservices written "
        "in .NET 8 with an Angular 17 single-page front-end. Services "
        "communicate synchronously via HTTPS REST and asynchronously via "
        "RabbitMQ using MassTransit. Persistence is per-service: PostgreSQL "
        "for transactional state, Redis for ephemeral caches and rate "
        "limiting, and ElasticSearch for searchable audit history."
    )

    p.h1("2. Service Inventory")
    p.table(
        ["Service", "Inbound", "Outbound", "Persistence"],
        [
            ["RegistrationService", "REST", "RabbitMQ, KYC HTTP", "Postgres"],
            ["FilingService", "REST", "RabbitMQ", "Postgres"],
            ["BillingService", "REST, RabbitMQ", "RabbitMQ", "Postgres"],
            ["PaymentService", "REST, RabbitMQ", "RabbitMQ", "Postgres"],
            ["ComplianceService", "RabbitMQ", "RabbitMQ", "Postgres, Redis"],
            ["NotificationService", "RabbitMQ", "SMTP, SMS gateway", "Redis"],
            ["AuditService", "RabbitMQ", "ElasticSearch", "ElasticSearch"],
        ],
        [42, 38, 50, 42],
    )

    p.h1("3. Tech Stack")
    p.bullets([
        "Runtime: .NET 8 LTS, ASP.NET Core minimal APIs and controllers.",
        "Frontend: Angular 17 with the Carbon Design System component library.",
        "Messaging: RabbitMQ 3.13 with MassTransit 8.x, durable queues and dead-letter exchanges.",
        "Database: PostgreSQL 16 with EF Core 8 and explicit migrations.",
        "Cache: Redis 7 (cluster mode) for session, rate limit and idempotency keys.",
        "Search: ElasticSearch 8 for audit and case search.",
        "Observability: OpenTelemetry, Grafana Tempo (traces), Loki (logs), Prometheus (metrics).",
        "CI/CD: Azure DevOps Pipelines deploying to AKS via Helm charts.",
    ])

    p.h1("4. Reference Module Layout")
    p.para(
        "Each service follows the same Domain Driven Design layering, "
        "named consistently to keep cross-team navigation predictable:"
    )
    p.bullets([
        "{Service}.Domain        - aggregates, value objects, domain events, repository interfaces.",
        "{Service}.Application   - command/query handlers (MediatR), validation, mappers.",
        "{Service}.Infrastructure- EF Core DbContext, MassTransit consumers, integration clients.",
        "{Service}.Presentation  - HTTP controllers, OpenAPI definitions, request/response DTOs.",
        "{Service}.Tests         - unit, integration and contract tests.",
    ])

    p.add_page()
    p.h1("5. Cross-Service Contracts")
    p.table(
        ["Event", "Producer", "Consumer(s)", "Transport"],
        [
            ["TaxpayerRegistered", "Registration", "Notification, Compliance", "RabbitMQ"],
            ["FilingSubmitted", "Filing", "Billing, Compliance", "RabbitMQ"],
            ["BillingCodeIssued", "Billing", "Notification", "RabbitMQ"],
            ["PaymentReceived", "Payment", "Billing, Compliance, Audit", "RabbitMQ"],
            ["ComplianceScoreChanged", "Compliance", "Audit, Officer Portal", "RabbitMQ"],
        ],
        [55, 35, 60, 30],
    )

    p.h1("6. Data Stores")
    p.para(
        "Each service owns its own schema. Cross-service joins are forbidden. "
        "Reference data (currency, tax rate, region) is replicated through "
        "an event-sourced reference data feed managed by the Platform Squad."
    )

    p.h1("7. Security")
    p.bullets([
        "OAuth2 + OIDC via the corporate identity provider; access tokens use the RS256 algorithm.",
        "Service-to-service calls use mTLS within the AKS service mesh.",
        "Secrets stored in Azure Key Vault and projected as environment variables at pod startup.",
        "All public endpoints behind WAF with OWASP Core Rule Set enabled.",
    ])

    p.h1("8. Performance Targets")
    p.bullets([
        "Sustained 4 000 requests per second across all public services.",
        "Filing calculation engine 95th percentile under 250 ms for filings up to 200 line items.",
        "Payment reconciliation end-to-end median latency under 60 seconds.",
    ])

    return p


def build_deployment() -> DemoPDF:
    p = DemoPDF("CoreTax Deployment Guide", "OPS-CT-2026-004")
    p.title_page(
        "CoreTax Modernisation Programme",
        "Deployment Guide and Runbook",
        "OPS-CT-2026-004",
        "1.0",
    )

    p.add_page()
    p.h1("1. Environments")
    p.table(
        ["Environment", "Purpose", "URL", "Promotion Source"],
        [
            ["dev", "Continuous integration", "dev.coretax.djp.go.id", "main branch"],
            ["sit", "System integration test", "sit.coretax.djp.go.id", "release/* branch"],
            ["uat", "User acceptance", "uat.coretax.djp.go.id", "manual from sit"],
            ["staging", "Pre-production rehearsal", "stg.coretax.djp.go.id", "approved release tag"],
            ["prod", "Production", "coretax.djp.go.id", "manual change advisory board"],
        ],
        [30, 50, 50, 50],
    )

    p.h1("2. Target Infrastructure")
    p.bullets([
        "Hosting: National Government Cloud, Indonesia Central region, three availability zones.",
        "Compute: Azure Kubernetes Service 1.29, system and user node pools, autoscaling 3 to 30 nodes.",
        "Database: Azure Database for PostgreSQL Flexible Server with zone-redundant HA.",
        "Cache: Azure Cache for Redis Premium, cluster mode, 6 shards.",
        "Search: Self-managed ElasticSearch 8 on dedicated VM scale set.",
        "Messaging: RabbitMQ cluster (3 nodes) on dedicated VMs, mirrored queues.",
        "Object storage: Azure Blob Storage with private endpoints.",
        "Networking: Hub-and-spoke VNet topology, ExpressRoute to partner Bank Persepsi VPCs.",
    ])

    p.h1("3. Helm Chart Layout")
    p.para(
        "Each service is packaged as its own Helm chart in the deploy "
        "monorepo under `charts/{service}`. The umbrella chart "
        "`charts/coretax-platform` references each service chart and pins "
        "image tags through the environment-specific values file."
    )
    p.bullets([
        "charts/registration-service/",
        "charts/filing-service/",
        "charts/billing-service/",
        "charts/payment-service/",
        "charts/compliance-service/",
        "charts/notification-service/",
        "charts/audit-service/",
        "charts/coretax-platform/values.{env}.yaml",
    ])

    p.add_page()
    p.h1("4. Deployment Procedure (Standard Release)")
    p.bullets([
        "1. Release captain creates a release branch from main: release/yyyy-mm-dd.",
        "2. CI pipeline builds and pushes versioned images to the private registry.",
        "3. Helm chart values.sit.yaml is updated with the new image tags and merged.",
        "4. The CD pipeline deploys to sit and runs the smoke test suite.",
        "5. After sit sign-off the same artefacts are promoted to uat (no rebuild).",
        "6. Change Advisory Board approves promotion to staging then production.",
        "7. Production deploy runs as a rolling update with maxSurge=1, maxUnavailable=0.",
        "8. Post-deploy verification suite runs against the production smoke endpoints.",
    ])

    p.h1("5. Configuration and Secrets")
    p.bullets([
        "Application configuration is loaded from ConfigMaps generated from values.{env}.yaml.",
        "Secrets are projected from Azure Key Vault via the CSI driver - never committed to git.",
        "Connection strings rotate every 90 days via the platform secret rotation job.",
    ])

    p.h1("6. Rollback Procedure")
    p.bullets([
        "1. Identify the last known good chart revision via `helm history coretax-platform`.",
        "2. Run `helm rollback coretax-platform <revision>` from the deploy runner.",
        "3. Verify health checks return 200 on every service.",
        "4. Open an incident ticket and capture the timeline in the post-mortem template.",
    ])

    p.h1("7. Operational Health Checks")
    p.bullets([
        "GET /health/live  - liveness probe, returns 200 when the process is up.",
        "GET /health/ready - readiness probe, returns 200 only when all dependencies are reachable.",
        "GET /metrics      - Prometheus scrape endpoint, exposes business and runtime metrics.",
    ])

    p.h1("8. Disaster Recovery")
    p.bullets([
        "Database point-in-time restore retained for 35 days.",
        "Cross-region read replicas warm in the secondary region with 5 minute RPO.",
        "DR drill executed at least twice per calendar year with documented runbook.",
    ])

    return p


def build_cicd() -> DemoPDF:
    p = DemoPDF("CoreTax CI/CD Pipeline", "ENG-CT-2026-005")
    p.title_page(
        "CoreTax Modernisation Programme",
        "Continuous Integration and Delivery Pipeline",
        "ENG-CT-2026-005",
        "1.0",
    )

    p.add_page()
    p.h1("1. Goals")
    p.bullets([
        "Every commit on main produces a deployable, signed container image.",
        "No manual steps between merge and dev environment availability.",
        "Production releases require explicit human approval and a clean security scan.",
        "Pipeline run time from commit to dev rollout under 12 minutes.",
    ])

    p.h1("2. Branching Model")
    p.bullets([
        "main           - protected, always deployable, no direct pushes.",
        "feature/*      - short-lived, merged via pull request with two reviewers.",
        "release/*      - cut from main when readying a versioned release.",
        "hotfix/*       - cut from the latest production tag for emergency fixes.",
    ])

    p.h1("3. Pipeline Stages")
    p.table(
        ["Stage", "Tool", "Gate"],
        [
            ["Lint and format", "dotnet format, eslint", "Hard fail"],
            ["Unit tests", "xUnit, Karma", "Coverage 80 percent or above"],
            ["SAST", "SonarQube, Semgrep", "No new critical findings"],
            ["Build container", "Docker BuildKit", "Image signed with Cosign"],
            ["Image scan", "Trivy", "No critical CVEs"],
            ["SBOM", "Syft", "SBOM uploaded to artifact store"],
            ["Integration tests", "Testcontainers", "All scenarios green"],
            ["Contract tests", "Pact broker", "All consumer contracts honoured"],
            ["Deploy to dev", "Helm + Argo CD", "Smoke suite green"],
        ],
        [60, 60, 60],
    )

    p.add_page()
    p.h1("4. Quality Gates")
    p.bullets([
        "Pull requests require a green build and at least two approvals from CODEOWNERS.",
        "SonarQube quality gate must pass with no new bugs, vulnerabilities or code smells.",
        "Test coverage must not drop more than 0.5 percent from main.",
        "Any change to a database migration requires the Data Steward as a reviewer.",
    ])

    p.h1("5. Promotion Flow")
    p.bullets([
        "dev    - automatic on every merge to main.",
        "sit    - automatic when the integration suite is green for at least 30 minutes on dev.",
        "uat    - manual trigger by the QA lead, image tag identical to sit.",
        "staging- manual trigger by the release captain, requires Change Advisory Board ticket.",
        "prod   - manual approval by the Operations Director.",
    ])

    p.h1("6. Secrets and Signing")
    p.bullets([
        "All build secrets are pulled from Azure Key Vault via federated identity, never stored in pipeline variables.",
        "Container images are signed with Cosign using a hardware-backed key.",
        "The Argo CD application controller verifies signatures before applying changes to the cluster.",
    ])

    p.h1("7. Observability of the Pipeline")
    p.bullets([
        "Pipeline metrics are exported to Prometheus and visualised in the Engineering Health dashboard.",
        "Failure rate, lead time for change, and mean time to recovery are reported weekly.",
        "Flaky tests are auto-quarantined after three intermittent failures and a Jira ticket is opened.",
    ])

    p.h1("8. Compliance Hooks")
    p.bullets([
        "Every production deploy is recorded in the change ledger with the approver, timestamp and image digest.",
        "Quarterly evidence pack is generated automatically for ISO 27001 surveillance audits.",
        "Incident retrospectives reference the exact pipeline run that introduced the regression.",
    ])

    return p


# ── Entrypoint ───────────────────────────────────────────────────────────


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    builders = {
        "CoreTax_BRD.pdf": build_brd,
        "CoreTax_FSD.pdf": build_fsd,
        "CoreTax_TSD.pdf": build_tsd,
        "CoreTax_Deployment_Guide.pdf": build_deployment,
        "CoreTax_CICD_Pipeline.pdf": build_cicd,
    }
    for filename, builder in builders.items():
        path = OUTPUT_DIR / filename
        pdf = builder()
        pdf.output(str(path))
        print(f"  wrote {path.relative_to(Path.cwd()) if path.is_absolute() else path}")
    print(f"\nGenerated {len(builders)} demo PDFs in {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
